/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  docs: [
    'build-api-quick-start-guide',
    {
      type: 'category',
      label: 'Building Apps',
      link: {
        type: 'generated-index',
        description: "Learn how to build content api in both graphql and rest by using apito console",
        keywords: ['guides', 'how-to', 'documentation'],
        image: '/img/docusaurus.png',
      },
      items: [
          'build-apps/building-a-todo-app-with-apito-with-both-rest-and-graphql-api'
      ]
    },
    {
      type: 'category',
      label: 'Apito Console Howto',
      link: {
        type: 'generated-index',
        description: "Learn how to build content api in both graphql and rest by using apito console",
        keywords: ['guides', 'how-to', 'documentation'],
        image: '/img/docusaurus.png',
      },
      items: [
        'console/how-to-design-database-for-your-project',
        'console/usages-of-swagger-and-graphql-explorer',
        'console/adding-multilingual-support-to-your-api',
        'console/adding-rbac-role-based-permissions-support-to-your-api',
        'console/api-integration-with-your-application'
        //'console/authentication',
        //'console/custom-function'
      ],
    },
    {
      type: 'category',
      label: 'Framework Integration',
      link: {
        type: 'generated-index',
        description: "Build websites your favorite frontend frameworks, or static site generators and host your websites on your favourite providers. No vendor lock-in.",
        keywords: ['guides', 'how-to'],
        image: '/img/docusaurus.png',
      },
      items: [
        'frameworks/gatsby-cms-with-graphql',
        'frameworks/vuejs-integration-with-graphql',
        'frameworks/nuxtjs-integration-with-graphql',
        'frameworks/nextjs-integration-with-graphql',
        'frameworks/reactjs-integration-with-graphql',
        'frameworks/angularjs-integration-with-graphql'
      ]
    },
    {
      type: 'category',
      label: 'Content/Database Modeling',
      link: {
        type: 'generated-index',
        description: "Learn effective ways to models for your content when building a content api. Learn the difference between single vs multi page models and how it affects your content",
        keywords: ['guides', 'how-to', 'documentation'],
        image: '/img/docusaurus.png',
      },
      items: [
        'model/database-design',
        'model/choice-between-models'
      ],
    },
    {
      type: 'category',
      label: 'Auto Deploy Pipeline',
      link: {
        type: 'generated-index',
        description: "Create Auto Deployments with Webhooks",
        keywords: ['guides', 'how-to', 'documentation'],
        image: '/img/docusaurus.png',
      },
      items: [
        'webhooks/create-webhooks',
        'webhooks/website-deployment-using-gitlab-pipeline',
        'webhooks/website-deployment-using-vercel-pipeline',
        'webhooks/website-deployment-using-netlify-build-hooks'
      ],
    },
    /*    {
          type: 'category',
          label: 'Building Apps',
          items: [
            {
              type: 'category',
              label: 'Ecommerce',
              items: [
                'apps/ecommerce/intro',
                'apps/ecommerce/designing-models',
                'apps/ecommerce/adding-relations-between-models',
                'apps/ecommerce/adding-authentication',
                'apps/ecommerce/writing-business-logic',
                'apps/ecommerce/configuring-roles-permissions',
                'apps/ecommerce/generating-api-secrets',
                'apps/ecommerce/connecting-api-to-frontend'
              ],
            },
          ],
        },*/
    {
      type: 'category',
      label: 'API Integration Guide',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'category',
          label: 'RESTful API',
          link: {
            type: 'generated-index',
            description: "REST is the most logical, efficient and widespread standard in the creation of APIs for Internet services.",
            keywords: ['guides', 'how-to', 'rest api', 'restful api', 'api integration'],
            image: '/img/docusaurus.png',
          },
          items: [
            'api-integration/restapi/integration-with-java',
            'api-integration/restapi/integration-with-android',
            'api-integration/restapi/integration-with-ios',
            'api-integration/restapi/integration-with-flutter',
            'api-integration/restapi/integration-with-golang',
            'api-integration/restapi/integration-with-csharp',
            'api-integration/restapi/integration-with-javascript',
            'api-integration/restapi/integration-with-php',
            'api-integration/restapi/integration-with-python',
            'api-integration/restapi/integration-with-ruby'
          ],
        },
        {
          type: 'category',
          label: 'GraphQL Client',
          link: {
            type: 'generated-index',
            description: "GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more",
            keywords: ['guides', 'how-to', 'graphql client', 'graphql api', 'api integration', 'graphql server'],
            image: '/img/docusaurus.png',
          },
          items: [
            'api-integration/graphql/integration-with-java',
            'api-integration/graphql/integration-with-android',
            'api-integration/graphql/integration-with-ios',
            'api-integration/graphql/integration-with-flutter',
            'api-integration/graphql/integration-with-golang',
            //'graphql/integration-with-csharp',
            'api-integration/graphql/integration-with-react',
            'api-integration/graphql/integration-with-php',
            'api-integration/graphql/integration-with-python',
            'api-integration/graphql/integration-with-ruby'
          ],
        },
      ],
    },
    /* {
       type: 'category',
       label: 'Configuring Cloud Providers',
       items: [
         {
           type: 'category',
           label: 'AWS',
           items: [
             'cloud-provider/aws/configuring-aws',
           ],
         }
       ],
     }*/

    {
      type: 'category',
      label: 'Extending Apito',
      link: {
        type: 'generated-index',
        description: "You can extend Apito with Various different plugins available in Settings. You can even extend apito api through cloud functions, add auth support and many more.",
        keywords: ['guides', 'how-to'],
        image: '/img/docusaurus.png',
      },
      items: [
        {
          type: 'category',
          label: 'Adding Authentication Support',
          link: {
            type: 'generated-index',
            description: "If you app contents are protected then you can extend Apito to be able to add login and signup functionality for your app users.",
            keywords: ['guides', 'how-to', 'auth', 'login api', 'signup api'],
            image: '/img/docusaurus.png',
          },
          items: [
            'extensions/auth/auth-support-in-api',
            'extensions/auth/register',
            'extensions/auth/login',
            'extensions/auth/using-login-token'
          ],
        },
        {
          type: 'category',
          label: 'Using Cloud Functions',
          link: {
            type: 'generated-index',
            description: "Cloud function makes a Headless CMS very extensible, robust & powerful. You can easily extend your existing graphql & restful api by using cloud functions.",
            keywords: ['guides', 'how-to', 'auth', 'login api', 'signup api'],
            image: '/img/docusaurus.png',
          },
          items: [
            'extensions/logic/configuring-aws',
            'extensions/logic/writing-cloud-functions',
            'extensions/logic/enable-lambda-extension',
            'extensions/logic/create-apito-function',
            'extensions/logic/create-lambda-function',
            'extensions/logic/connecting-function',
            'extensions/logic/calling-function'
          ],
        },
      ],
    },
    'using-apito-as-backend-as-service',
  ],
};

module.exports = sidebars;
